# Generated by Django 5.0.9 on 2026-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_couponusage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='discounts_c_is_acti_24cb30_idx',
            old_name='discounts_c_isactv_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='discounts_c_coupon__fcc2f5_idx',
            old_name='discounts_cu_coupon_user_idx',
        ),
    ]
