# Generated by Django 5.0.9 on 2026-10-02 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_options_alter_category_created_at_and_more'),
        ('discounts', '0003_rename_discounts_c_isactv_exp_idx_discounts_c_is_acti_24cb30_idx_and_more'),
        ('orders', '0004_order_stock_restored_at_order_tracking_code'),
        ('products', '0004_alter_brand_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'کوپن تخفیف', 'verbose_name_plural': 'کوپن\u200cهای تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='couponusage',
            options={'ordering': ['-used_at'], 'verbose_name': 'استفاده از کوپن', 'verbose_name_plural': 'استفاده\u200cهای کوپن'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='خالی = روی همهٔ فروشگاه اعمال می\u200cشود.', related_name='coupons', to='categories.category', verbose_name='دسته\u200cبندی\u200cهای مشمول'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='خالی = روی همهٔ فروشگاه اعمال می\u200cشود.', related_name='coupons', to='products.product', verbose_name='محصولات مشمول'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='کدی که مشتری هنگام خرید وارد می\u200cکند.', max_length=32, unique=True, verbose_name='کد کوپن'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=10, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='fixed_value',
            field=models.PositiveBigIntegerField(blank=True, help_text='برای کوپن مبلغ ثابت لازم است.', null=True, verbose_name='مبلغ تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='به\u200cجای حذف، برای غیرفعال\u200cکردن موقت استفاده می\u200cشود.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='maximum_discount_amount',
            field=models.PositiveBigIntegerField(blank=True, help_text='بیشینهٔ تخفیف کوپن\u200cهای درصدی. برای کوپن مبلغ ثابت نادیده گرفته می\u200cشود.', null=True, verbose_name='سقف تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.PositiveBigIntegerField(blank=True, help_text='جمع اقلام باید حداقل به این مبلغ برسد تا کوپن اعمال شود.', null=True, verbose_name='حداقل مبلغ سفارش (تومان)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='per_user_usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر تعداد استفاده برای هر کاربر. خالی = نامحدود.', null=True, verbose_name='سقف استفادهٔ هر کاربر'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentage_value',
            field=models.PositiveSmallIntegerField(blank=True, help_text='برای کوپن درصدی لازم است؛ عددی بین ۱ تا ۱۰۰.', null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر تعداد استفاده برای همهٔ کاربران. خالی = نامحدود.', null=True, verbose_name='سقف استفادهٔ کل'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.coupon', verbose_name='کوپن'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان استفاده'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
