# Generated by Django 5.0.9 on 2026-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='categories__parent__85acd9_idx',
            old_name='categories__parent__idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='categories__is_acti_baf376_idx',
            old_name='categories__isactv_ord_idx',
        ),
    ]
