# Generated by Django 5.0.9 on 2026-10-02 17:54

import apps.core.image_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_categories__parent__idx_categories__parent__85acd9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[apps.core.image_files.validate_image_file]),
        ),
    ]
