# Generated by Django 5.0.9 on 2026-10-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_options_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=170, unique=True, verbose_name='شناسه (آدرس)'),
        ),
    ]
