# Generated by Django 5.0.9 on 2026-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banner',
            new_name='banners_ban_is_acti_ab27e3_idx',
            old_name='banners_b_isactv_ord_idx',
        ),
        migrations.RenameIndex(
            model_name='dailydeal',
            new_name='banners_dai_is_acti_fcd2c8_idx',
            old_name='banners_dd_active_range_idx',
        ),
    ]
