# Generated by Django 5.0.9 on 2026-10-02 17:54

import apps.core.image_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_rename_banners_b_isactv_ord_idx_banners_ban_is_acti_ab27e3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[apps.core.image_files.validate_image_file]),
        ),
    ]
