# Generated by Django 5.0.9 on 2026-10-02 18:09

import apps.core.image_files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_banner_image'),
        ('products', '0004_alter_brand_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['ordering'], 'verbose_name': 'بنر', 'verbose_name_plural': 'بنرها'},
        ),
        migrations.AlterModelOptions(
            name='dailydeal',
            options={'ordering': ['-starts_at'], 'verbose_name': 'پیشنهاد روزانه', 'verbose_name_plural': 'پیشنهادهای روزانه'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='متن دکمهٔ اقدام'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='cta_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='لینک دکمهٔ اقدام'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان نمایش'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[apps.core.image_files.validate_image_file], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='به\u200cجای حذف، برای غیرفعال\u200cکردن موقت استفاده می\u200cشود.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر زودتر نمایش داده می\u200cشود.', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع نمایش'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='dailydeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='dailydeal',
            name='ends_at',
            field=models.DateTimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='dailydeal',
            name='is_active',
            field=models.BooleanField(default=True, help_text='به\u200cجای حذف، برای غیرفعال\u200cکردن موقت استفاده می\u200cشود.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='dailydeal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_deals', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='dailydeal',
            name='sale_price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت پیشنهاد روزانه (تومان)'),
        ),
        migrations.AlterField(
            model_name='dailydeal',
            name='starts_at',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='dailydeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
