# Generated by Django 5.0.9 on 2026-10-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_banner_options_alter_dailydeal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='webp_1200',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='webp_400',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='webp_800',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
