# Generated by Django 5.0.9 on 2026-10-03 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_refund_amount_order_refund_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('event', models.CharField(help_text='Machine name of the event, e.g. order_confirmed / order_shipped / password_reset. See apps/notifications/services.py Events.', max_length=40, verbose_name='رویداد')),
                ('channel', models.CharField(choices=[('sms', 'پیامک'), ('email', 'ایمیل')], max_length=10, verbose_name='کانال')),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال'), ('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('skipped', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('recipient_masked', models.CharField(help_text='Phone/email of the recipient, masked -- raw contact data is never duplicated into the audit log.', max_length=120, verbose_name='گیرنده (ماسک\u200cشده)')),
                ('error', models.TextField(blank=True, default='', verbose_name='خطا')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=64, verbose_name='شناسهٔ پیام نزد ارائه\u200cدهنده')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش اعلان',
                'verbose_name_plural': 'گزارش اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='notificatio_event_665ecd_idx'), models.Index(fields=['order'], name='notificatio_order_i_1933ed_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('event', 'order', 'channel'), name='unique_notification_per_event_order_channel'),
        ),
    ]
