# Generated by Django 5.0.9 on 2026-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='cart_cartit_cart_id_4fb076_idx',
            old_name='cart_ci_cart_idx',
        ),
    ]
