# Generated by Django 5.0.9 on 2026-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='تلفن پشتیبانی')),
                ('whatsapp', models.CharField(blank=True, default='', help_text='شمارهٔ کامل با کد کشور، مثال: +989120000000', max_length=40, verbose_name='واتس\u200cاپ')),
                ('telegram', models.CharField(blank=True, default='', help_text='نام کاربری یا لینک، مثال: cusin_gallery یا https://t.me/cusin_gallery', max_length=80, verbose_name='تلگرام')),
                ('instagram', models.CharField(blank=True, default='', help_text='نام کاربری یا لینک صفحهٔ اینستاگرام', max_length=80, verbose_name='اینستاگرام')),
                ('address', models.TextField(blank=True, default='', verbose_name='نشانی فروشگاه')),
                ('working_hours', models.CharField(blank=True, default='', max_length=120, verbose_name='ساعات پاسخگویی')),
                ('pickup_address', models.TextField(blank=True, default='', help_text='برای روش ارسال «حضوری» در checkout و فاکتور نمایش داده می\u200cشود.', verbose_name='نشانی دریافت حضوری')),
                ('pickup_hours', models.CharField(blank=True, default='', max_length=120, verbose_name='ساعات دریافت حضوری')),
                ('enamad_html', models.TextField(blank=True, default='', help_text='اسنیپت embed را از پنل enamad.ir کپی و اینجا ذخیره کنید؛ عیناً در فوتر رندر می\u200cشود. خالی = نمایش جای خالی علامت\u200cگذاری\u200cشده.', verbose_name='کد نماد اعتماد (e-namad)')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
    ]
