# Generated by Django 5.0.9 on 2026-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_02a211_idx',
            old_name='orders_o_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c50fb7_idx',
            old_name='orders_o_status_pay_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_0e92de_idx',
            old_name='orders_o_created_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_5d347b_idx',
            old_name='orders_oi_order_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_product_32ff41_idx',
            old_name='orders_oi_product_idx',
        ),
    ]
