# Generated by Django 5.0.9 on 2026-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_estimated_delivery_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
