# Generated by Django 5.0.9 on 2026-10-02 18:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_coupon_options_alter_couponusage_options_and_more'),
        ('orders', '0004_order_stock_restored_at_order_tracking_code'),
        ('products', '0004_alter_brand_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'قلم سفارش', 'verbose_name_plural': 'اقلام سفارش'},
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.coupon', verbose_name='کوپن تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_max',
            field=models.DateField(blank=True, null=True, verbose_name='دیرترین تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_min',
            field=models.DateField(blank=True, null=True, verbose_name='زودترین تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='شمارهٔ سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('refunded', 'مسترد شده')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_building_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینهٔ ارسال (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='standard', max_length=20, verbose_name='روش ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(max_length=20, verbose_name='تلفن گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(max_length=20, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_recipient_name',
            field=models.CharField(max_length=150, verbose_name='نام گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بازگشت موجودی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveBigIntegerField(verbose_name='جمع اقلام (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ نهایی (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='پیش از تغییر وضعیت به «ارسال شده» وارد کنید.', max_length=100, verbose_name='کد رهگیری پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(max_length=64, verbose_name='کد کالا (SKU)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveBigIntegerField(verbose_name='جمع ردیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت واحد (تومان)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant', verbose_name='تنوع'),
        ),
    ]
