# Generated by Django 5.0.9 on 2026-10-02 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_coupon_options_alter_couponusage_options_and_more'),
        ('orders', '0005_alter_order_options_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.PositiveBigIntegerField(default=0, help_text='مجموع مبالغی که باید به مشتری بازگردانده شود (تومان).', verbose_name='مبلغ بازپرداخت (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reference',
            field=models.TextField(blank=True, default='', help_text='شرح رویدادهای بازپرداخت (به\u200cصورت تجمعی) و در نهایت مرجع/یادداشت بازپرداخت دستی در پنل درگاه. بدون افزودن یادداشت نمی\u200cتوان سفارش را «بازپرداخت شده» کرد.', verbose_name='یادداشت بازپرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('none', 'بدون بازپرداخت'), ('required', 'نیازمند بازپرداخت'), ('refunded', 'بازپرداخت شده')], default='none', max_length=10, verbose_name='وضعیت بازپرداخت وجه'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بازپرداخت'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['refund_status'], name='orders_orde_refund__b53440_idx'),
        ),
    ]
