# Generated by Django 5.0.9 on 2026-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_refund_amount_order_refund_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.TextField(blank=True, default='', help_text='حداکثر ۲۰۰ کاراکتر؛ متن ساده -- در همهٔ نمایش\u200cها escape می\u200cشود.', verbose_name='پیام هدیه'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_wrap',
            field=models.BooleanField(default=False, verbose_name='بسته\u200cبندی هدیه'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_wrap_fee',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینهٔ بسته\u200cبندی هدیه (تومان)'),
        ),
    ]
