"""
Adds User.phone (Phase 2). See apps/accounts/models.py for the field
definition this must match, and the Phase 1 README's "Honesty note" for
why this was hand-authored rather than generated by `makemigrations`
(no Django/network access in the sandbox that built it) -- run
`python manage.py makemigrations --check --dry-run accounts` before
relying on it.
"""
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Optional for now; a required/verified phone number is a Phase 3 decision.",
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (digits only, optionally prefixed with +).",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
            ),
        ),
    ]
