# Generated by Django 5.0.9 on 2026-10-02 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text="Required for customer self-registration (enforced in RegisterSerializer); nullable here because staff/superuser accounts aren't required to have one.", max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits only, optionally prefixed with +).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
