# Generated by Django 5.0.9 on 2026-10-03 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان مصرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد بازیابی رمز (پیامکی)',
                'verbose_name_plural': 'کدهای بازیابی رمز (پیامکی)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_ph_user_id_fd1a5b_idx')],
            },
        ),
    ]
