# Generated by Django 5.0.9 on 2026-10-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phoneresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_sms_consent',
            field=models.BooleanField(default=False, help_text='فقط با روشن\u200cکردن توسط خود مشتری در صفحهٔ حساب کاربری؛ برای پیامک یادآور سبد خرید.', verbose_name='رضایت دریافت پیامک تبلیغاتی'),
        ),
    ]
