# Generated by Django 5.0.9 on 2026-10-06 06:23

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_marketing_sms_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(max_length=20, validators=[apps.accounts.validators.validate_building_number], verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='address',
            name='unit',
            field=models.CharField(help_text='اگر واحد ندارید عدد ۰ را وارد کنید.', max_length=20, validators=[apps.accounts.validators.validate_unit], verbose_name='واحد'),
        ),
    ]
