# Generated by Django 5.0.9 on 2026-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='wishlist_wi_user_id_1fe9fd_idx',
            old_name='wishlist_wi_user_idx',
        ),
    ]
