# Generated by Django 5.0.9 on 2026-10-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_wishlist_wi_user_idx_wishlist_wi_user_id_1fe9fd_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'علاقه\u200cمندی', 'verbose_name_plural': 'علاقه\u200cمندی\u200cها'},
        ),
    ]
