# Generated by Django 5.0.9 on 2026-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_product_0aaa55_idx',
            old_name='reviews_r_product_status_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_status_5966f7_idx',
            old_name='reviews_r_status_idx',
        ),
    ]
