# Generated by Django 5.0.9 on 2026-10-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_rename_orders_o_user_status_idx_orders_orde_user_id_02a211_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField(help_text='The order total captured at payment initiation (Toman). Verification compares against this, never against a client-supplied value.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('gateway', models.CharField(help_text='Identifier of the gateway implementation used for this attempt (settings.PAYMENT_GATEWAY at initiation time).', max_length=40)),
                ('gateway_transaction_id', models.CharField(blank=True, default='', help_text="The gateway's own transaction handle (e.g. an 'authority' code). Callback handling looks the payment up by this, never by our own id.", max_length=128)),
                ('gateway_ref_id', models.CharField(blank=True, default='', help_text="The gateway's final verification reference (receipt id), set only after a successful verify call.", max_length=128)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gateway_transaction_id'], name='payments_pa_gateway_2a3159_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('order',), name='unique_successful_payment_per_order'),
        ),
    ]
