# Generated by Django 5.0.9 on 2026-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_pan',
            field=models.CharField(blank=True, default='', help_text='Masked paying-card number as returned by the gateway on verification. Never a full PAN.', max_length=32, verbose_name='شماره کارت (ماسک\u200cشده)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_pan_hash',
            field=models.CharField(blank=True, default='', help_text="Gateway-provided hash (fingerprint) of the paying card, e.g. ZarinPal's card_hash. Not card data -- a one-way digest for support/reconciliation.", max_length=64, verbose_name='اثر انگشت کارت'),
        ),
    ]
