# Generated by Django 5.0.9 on 2026-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_2fee29_idx',
            old_name='products_p_isactv_feat_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_beb3df_idx',
            old_name='products_p_isactv_new_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_33d395_idx',
            old_name='products_p_isactv_best_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_50f5f1_idx',
            old_name='products_p_categ_isactv_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_brand_i_8f789e_idx',
            old_name='products_p_brand_isactv_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_price_9b1a5f_idx',
            old_name='products_p_price_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_66459e_idx',
            old_name='products_pv_prod_isactv_idx',
        ),
    ]
