# Generated by Django 5.0.9 on 2026-10-02 17:54

import apps.core.image_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_p_isactv_feat_idx_products_pr_is_acti_2fee29_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='products/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', validators=[apps.core.image_files.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[apps.core.image_files.validate_image_file]),
        ),
    ]
