# Generated by Django 5.0.9 on 2026-10-04 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_brand_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackInStockSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شمارهٔ موبایل باید به شکل 09xxxxxxxxx (۱۱ رقم) باشد.', regex='^09\\d{9}$')], verbose_name='شمارهٔ موبایل')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اطلاع\u200cرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_in_stock_subscriptions', to='products.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_in_stock_subscriptions', to='products.productvariant', verbose_name='تنوع')),
            ],
            options={
                'verbose_name': 'اطلاع\u200cرسانی موجودی',
                'verbose_name_plural': 'اطلاع\u200cرسانی\u200cهای موجودی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='backinstocksubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('notified_at__isnull', True)), fields=('phone', 'product', 'variant'), name='one_active_back_in_stock_per_phone_and_item'),
        ),
    ]
