# Generated by Django 5.0.9 on 2026-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_backinstocksubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='webp_1200',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='webp_400',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='webp_800',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
