# Generated by Django 5.0.9 on 2026-10-04 21:03

import apps.core.image_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_webp_1200_productimage_webp_400_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='برند ویژه (کاشی صفحه اصلی)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tile_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/tiles/', validators=[apps.core.image_files.validate_image_file], verbose_name='تصویر کاشی'),
        ),
        migrations.AddField(
            model_name='brand',
            name='webp_1200',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='webp_400',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='webp_800',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
