# Generated by Django 5.0.9 on 2026-10-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand_display_order_brand_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_name',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='نام نرمال\u200cشده (رتبه\u200cبندی جستجو)'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='متن جستجوی نرمال\u200cشده'),
        ),
    ]
