# Generated by Django 5.0.9 on 2026-10-05 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_search_name_product_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complements',
            field=models.ManyToManyField(blank=True, help_text='کالاهایی که در صفحهٔ این محصول به\u200cعنوان «پیشنهاد همراه» نمایش داده می\u200cشوند.', related_name='complemented_by', to='products.product', verbose_name='پیشنهادهای همراه (دستی)'),
        ),
        migrations.CreateModel(
            name='FrequentlyBoughtTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('co_count', models.PositiveIntegerField(default=0, verbose_name='تعداد خرید همراه')),
                ('complement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_as_complement', to='products.product', verbose_name='کالای همراه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_pairs', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'خرید همراه (خودکار)',
                'verbose_name_plural': 'خریدهای همراه (خودکار)',
                'ordering': ['-co_count'],
            },
        ),
        migrations.AddConstraint(
            model_name='frequentlyboughttogether',
            constraint=models.UniqueConstraint(fields=('product', 'complement'), name='unique_fbt_pair'),
        ),
    ]
